### ISSUE TITLE
Проблемы с запуском

### ISSUE THREAD

**Issue by Kotemorte** [alanrbtx/llmclone#1]
Я сделал небольшой скрипт для всего этого.

```
from clone import process_tg_data, LLMClone, train_clone, CloneConfig

def main():
    # Подготовка данных
    file_path = "result.json"  # Укажите путь к файлу данных Telegram
    user_name = "Name"  # Укажите ваше имя пользователя в Telegram

    dataset = process_tg_data(file_path=file_path, user=user_name, output_format="dataset")

    # Инициализация модели
    config = CloneConfig(
        model_name="huggyllama/llama-7b",
        quantized=True
    )
    clone = LLMClone(config)

    # Обучение модели
    train_clone(clone, dataset)

    # Генерация ответов
    prompt = """
    User: Чем занимаешься?
    """
    response = clone.sample(prompt)
    print(response)

    # Добавление адаптеров (если необходимо)
    # clone.add_adapters("clone_peft")

if __name__ == "__main__":
    main()

```
Я запускаю скрипт и получаю в терминале ошибочку
Traceback (most recent call last):
  File "C:\find2er2\pythonProject13423\llmclone\main2.py", line 32, in <module>
    main()
  File "C:\find2er2\pythonProject13423\llmclone\main2.py", line 16, in main
    clone = LLMClone(config)
  File "C:\find2er2\pythonProject13423\llmclone\clone\clone\clone_model.py", line 17, in __init__
    self._build_clone()
  File "C:\find2er2\pythonProject13423\llmclone\clone\clone\clone_model.py", line 31, in _build_clone
    self.model = AutoModelForCausalLM.from_pretrained(
  File "C:\find2er2\pythonProject13423\venv\lib\site-packages\transformers\models\auto\auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
  File "C:\find2er2\pythonProject13423\venv\lib\site-packages\transformers\modeling_utils.py", line 2897, in from_pretrained
    raise RuntimeError("No GPU found. A GPU is needed for quantization.")
RuntimeError: No GPU found. A GPU is needed for quantization.

Process finished with exit code 1

Я использую PyCharm и среду venv
Я прошел через шаги
git clone https://github.com/alanrbtx/llmclone.git
cd llmclone
pip install -r requirements.txt

Если что у меня GTX 1060 на 6GB ...

**Comment by alanrbtx** [comment]
Возможно конфликт версий пакетов и драйверов, пока что можете запустить пример из коллаба

**Comment by matwej29** [comment]
BitsAndBytes работает только на linux. Через WSL будет работать
